# Generated by Django 6.0.5 on 2026-06-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_skill_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('issuer', models.CharField(max_length=255)),
                ('date', models.CharField(blank=True, max_length=100)),
                ('credential_url', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
